package net.lacnic.web.registro.api.request;

public enum Operacion {

	ORG_CAMBIAR_INFO,
	ORG_CAMBIAR_PUNTOS_CONTACTO,
	
	CONTACTO_CAMBIAR_INFO,
	
	BLOQUE_CAMBIAR_PUNTOS_CONTACTO,
	BLOQUE_DELEGAR_REVERSOS,
	BLOQUE_REASIGANAR,
	BLOQUE_EDITAR,
	BLOQUE_ELIMINAR,
	
	INGRESAR_SOLICITUD;
}